### PR TITLE
Misc. fixes, partly to work with newer Gerrit versions

### PR DESCRIPTION
**Pull request by sschuberth**
Please see the individual commit messages for the details.

### CODE REVIEW

**Comment by andygrunwald** [comment]
This changes are looking great. Thank you!

**Comment by sschuberth** [comment]
Wow, thanks for the fast merge! .-)

Note that still more work would be required to get the pagination work with newer versions of Gerrit. These changes only make Gerrie work without throwing an exception, but results may be incomplete.

**Comment by andygrunwald** [comment]
Thank you for this additional note @sschuberth.
In my spare time i am working on [watson](https://github.com/andygrunwald/watson), a  crawler for Googles code review system "Gerrit".

At the first view it looks like a "copy" of Gerrie, but it is not.
watson focus on "easier usage". I recognized that get Gerrie up and running and establish ssh connections might be difficult (or for some Gerrit instance like Google ones impossible, because they don`t support SSH access).

The goal of watson is easier usage (e.g. there is no need for a PHP installation, just download the cross compiled binary and start). Next to this it supports only the REST-API that drops all requirements of setting up a SSH connection directly.

Of course, watson is still in development and not production ready yet, but maybe it is interesting for you.

**Comment by sschuberth** [comment]
Thanks @andygrunwald for pointing me at watson. If you're saying that Gerrie is more or less deprecated, and you won't add new features (like pagination support) to it, maybe you should say so in the README and include a link to watson, even if watson is not production read yet?

**Comment by andygrunwald** [comment]
Good point. I added a deprecation notice. See https://github.com/andygrunwald/Gerrie/commit/83c979246f39f8b3dee4f19b7a5e977bcbe52d9f

Are they any requests from your side regarding watson?
Do you would use watson instead of Gerrie?

**Comment by sschuberth** [comment]
I don't have any requests regarding watson as I haven't tried it out yet :-) But if so, I'll file an issue over there. Does watson already support Gerrit >= 2.10 style pagination with offsets instead of sort keys?

BTW: What was the rational to use Go instead of PHP for watson? (Something that maybe could go into watson's README?)

**Comment by andygrunwald** [comment]
Hey @sschuberth,

sorry for the long outstanding answer.
Sadly, i don`t had the time to continue the work on watson. But i am sure that i will continue this in future.

> Does watson already support Gerrit >= 2.10 style pagination with offsets instead of sort keys?
Afaik, yes it does.

> BTW: What was the rational to use Go instead of PHP for watson? (Something that maybe could go into watson's README?)
My main reason was that Gerrie is quite hard to deploy for new people (especially the SSH key thingy). With Go a single binary it is "just" download and go.
Next to this i wanted to learn Golang.
And as a third reason: By using HTTP only we are able to crawl Gerrit instances like Golang, Android, etc. (Hosted on Googlecode)

**Pull request merged**
